"""add ndvi window columns

Revision ID: e2ff0391b90e
Revises: 3aa6c82dd67c
Create Date: 2026-07-22 13:51:45.087986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ff0391b90e'
down_revision: Union[str, None] = '3aa6c82dd67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ndvi_history', sa.Column('date_range_start', sa.Date(), nullable=True))
    op.add_column('ndvi_jobs', sa.Column('requested_start_date', sa.Date(), nullable=True))
    op.add_column('ndvi_jobs', sa.Column('requested_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ndvi_jobs', 'requested_end_date')
    op.drop_column('ndvi_jobs', 'requested_start_date')
    op.drop_column('ndvi_history', 'date_range_start')
    # ### end Alembic commands ###
