"""add field irrigation sowing columns

Revision ID: 0961769700e5
Revises: 3e6488b19ccb
Create Date: 2026-07-28 13:18:57.706985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0961769700e5'
down_revision: Union[str, None] = '3e6488b19ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('irrigation_type', sa.String(length=20), nullable=True))
    op.add_column('fields', sa.Column('sowing_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'sowing_date')
    op.drop_column('fields', 'irrigation_type')
    # ### end Alembic commands ###
