"""add and seed mandi rates

Revision ID: 9c176e8524fd
Revises: a857828af3db
Create Date: 2026-07-10 09:02:58.574298

Seed values are copied verbatim from the design's mock `market` array
(design_handoff/designs/Jadeed Kashtkar App.dc.html, ~line 904) — the
Faisalabad reference price, change %, and 7-day sparkline. Per GAPS.md
Gap 7, a real market-data integration is out of scope for now.
"""
import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c176e8524fd'
down_revision: Union[str, None] = 'a857828af3db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


mandi_rate_table = sa.table(
    "mandi_rates",
    sa.column("id", sa.UUID()),
    sa.column("commodity", sa.String),
    sa.column("urdu_name", sa.String),
    sa.column("base_price_pkr_per_40kg", sa.Float),
    sa.column("change_pct", sa.Float),
    sa.column("history_7d", sa.ARRAY(sa.Integer())),
    sa.column("updated_at", sa.DateTime(timezone=True)),
)

# (commodity, urdu_name, base_price_pkr_per_40kg, change_pct, history_7d)
SEED_ROWS = [
    ("Wheat", "گندم", 3920, 1.2, [40, 46, 44, 55, 60, 68, 82]),
    ("Basmati paddy", "باسمتی", 5410, -0.8, [80, 74, 70, 66, 60, 56, 50]),
    ("Cotton (phutti)", "پھٹی", 8540, 2.4, [30, 38, 36, 50, 58, 70, 88]),
    ("Sugarcane", "گنا", 462, 0.4, [50, 52, 48, 54, 55, 58, 60]),
    ("Maize", "مکئی", 2350, -1.1, [78, 72, 74, 64, 58, 50, 44]),
    ("Moong", "مونگ", 9100, 0.6, [44, 48, 46, 52, 56, 58, 62]),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mandi_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity', sa.String(length=64), nullable=False),
    sa.Column('urdu_name', sa.String(length=64), nullable=False),
    sa.Column('base_price_pkr_per_40kg', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=False),
    sa.Column('history_7d', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commodity')
    )
    # ### end Alembic commands ###

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        mandi_rate_table,
        [
            {
                "id": uuid.uuid4(),
                "commodity": commodity,
                "urdu_name": urdu_name,
                "base_price_pkr_per_40kg": price,
                "change_pct": chg,
                "history_7d": history,
                "updated_at": now,
            }
            for commodity, urdu_name, price, chg, history in SEED_ROWS
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mandi_rates')
    # ### end Alembic commands ###
