"""initial schema

Revision ID: 3da7f6c17f4f
Revises: 
Create Date: 2026-07-10 08:57:39.555174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3da7f6c17f4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district_yield_baseline',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('crop', sa.String(length=50), nullable=False),
    sa.Column('baseline_ndvi', sa.Float(), nullable=False),
    sa.Column('baseline_yield_maund_per_acre', sa.Float(), nullable=False),
    sa.Column('baseline_yield_t_per_ha', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district', 'crop', name='uq_district_yield_baseline_district_crop')
    )
    op.create_index(op.f('ix_district_yield_baseline_crop'), 'district_yield_baseline', ['crop'], unique=False)
    op.create_index(op.f('ix_district_yield_baseline_district'), 'district_yield_baseline', ['district'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('area_hectares', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('crop', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # Not created here: GeoAlchemy2's Geometry(spatial_index=True) (the
    # default) already emits its own GIST index via a DDL event when the
    # table is created — an explicit create_index here would duplicate it.
    op.create_index(op.f('ix_fields_user_id'), 'fields', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('yield_unit', sa.String(length=32), nullable=False),
    sa.Column('default_mandi', sa.String(length=64), nullable=False),
    sa.Column('alert_pest', sa.Boolean(), nullable=False),
    sa.Column('alert_weather', sa.Boolean(), nullable=False),
    sa.Column('alert_price', sa.Boolean(), nullable=False),
    sa.Column('alert_sms', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('ndvi_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('ndvi_mean', sa.Float(), nullable=False),
    sa.Column('ndvi_min', sa.Float(), nullable=False),
    sa.Column('ndvi_max', sa.Float(), nullable=False),
    sa.Column('ndmi_mean', sa.Float(), nullable=True),
    sa.Column('ndmi_min', sa.Float(), nullable=True),
    sa.Column('ndmi_max', sa.Float(), nullable=True),
    sa.Column('ndvi_png_url', sa.String(), nullable=True),
    sa.Column('ndmi_png_url', sa.String(), nullable=True),
    sa.Column('satellite_image_date', sa.Date(), nullable=False),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=True),
    sa.Column('source_collection', sa.String(length=255), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndvi_history_field_id'), 'ndvi_history', ['field_id'], unique=False)
    op.create_table('ndvi_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='ndvi_job_status'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('ndvi_history_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ndvi_history_id'], ['ndvi_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ndvi_jobs_field_id'), 'ndvi_jobs', ['field_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ndvi_jobs_field_id'), table_name='ndvi_jobs')
    op.drop_table('ndvi_jobs')
    op.drop_index(op.f('ix_ndvi_history_field_id'), table_name='ndvi_history')
    op.drop_table('ndvi_history')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_fields_user_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_district_yield_baseline_district'), table_name='district_yield_baseline')
    op.drop_index(op.f('ix_district_yield_baseline_crop'), table_name='district_yield_baseline')
    op.drop_table('district_yield_baseline')
    # ### end Alembic commands ###
